- hosts: all
  vars:
    personal: "{{ lookup('env', 'HOME') }}/personal"
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
  vars_files:
    - vars/vars.yml
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  roles:
    - core
  tasks:
    - include: tasks/git-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/slack-setup.yml
    - include: tasks/personal-projects.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/python.yml
