- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
    
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Ensure .antigen directory exists.
  file:
    dest: "/usr/local/share/antigen"
    mode: 0700
    state: directory
    recurse: yes
  become_user: chris
  tags: *tags_for_zsh_tasks

- name: Antigen
  shell: curl -L git.io/antigen > /usr/local/share/antigen/antigen.zsh
  tags: *tags_for_zsh_tasks
  become_user: chris
