- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: "{{ sys_packages_one | default(default_sys_packages_one) }}"
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: "{{ sys_packages_two | default(default_sys_packages_two) }}"
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: "{{ sys_packages_three | default(default_sys_packages_three) }}"
  tags:
    - install
    - core

- name: Install Clang
  become: true
  apt:
    name: "{{ clang_packages | default(default_clang_packages) }}"
  tags:
    - install
    - neovim
    - core
