---
- name: Converge
  hosts: all
  gather_facts: false
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - name: "Include core"
      include_role:
        name: "core"
