---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: williamyeh/ansible:ubuntu18.04
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
