---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
  - name: Ensure Chris User exists
    user:
      name: "chris"
      state: present
  - name: Ensure .ssh file is present
    file:
      path: "~/.ssh"
      state: directory
      mode: 0644
  - name: Generate Test SSH keys for Molecule
    openssh_keypair:
      path: "~/.ssh/id_rsa"
      type: rsa
      size: 4096
      state: present
      force: no
